CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SEQUENCE resourcehub.REF_SET_ID_SEQ START 1 INCREMENT 1;

CREATE TABLE REF_SET (
    ID UUID PRIMARY KEY DEFAULT "resourcehub".uuid_generate_v4(),
    REF_SET_ID INTEGER NOT NULL DEFAULT nextval('resourcehub.REF_SET_ID_SEQ'),
    REF_SET_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100) NOT NULL
);

CREATE SEQUENCE resourcehub.REF_TERM_ID_SEQ START 1 INCREMENT 1;

CREATE TABLE REF_TERM (
    ID UUID PRIMARY KEY DEFAULT "resourcehub".uuid_generate_v4(),
    REF_TERM_ID INTEGER NOT NULL DEFAULT nextval('resourcehub.REF_TERM_ID_SEQ'),
    REF_TERM_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    REF_SET_ID UUID NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100) NOT NULL,
    CONSTRAINT REF_SET_ID_FKEY FOREIGN KEY (REF_SET_ID) REFERENCES resourcehub.REF_SET(ID)
);

CREATE VIEW resourcehub.REF_SET_TERM_VIEW AS
SELECT
    RS.ID AS REF_SET_UUID,
    RS.REF_SET_ID AS REF_SET_NUM_ID,
    RS.REF_SET_NAME,
    RT.ID AS REF_TERM_UUID,
    RT.REF_TERM_ID AS REF_TERM_NUM_ID,
    RT.REF_TERM_NAME
FROM
    resourcehub.REF_SET RS
JOIN
    resourcehub.REF_TERM RT
ON
    RS.ID = RT.REF_SET_ID;
