CREATE TABLE FILE_PROCESSING_STATUS (
    ID UUID PRIMARY KEY DEFAULT "resourcehub".uuid_generate_v4(),
    FILE_NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    PROCESSED_ON TIMESTAMP
);

CREATE SEQUENCE resourcehub.ASSET_ID_SEQ START 1 INCREMENT 1;

CREATE TABLE ASSET (
    ID UUID PRIMARY KEY DEFAULT "resourcehub".uuid_generate_v4(),
    ASSET_ID INTEGER NOT NULL DEFAULT nextval('resourcehub.ASSET_ID_SEQ'),
    ASSET_TYPE_ID UUID NOT NULL,
    ASSET_NAME VARCHAR(100) NOT NULL,
    EXTENSION_TYPE VARCHAR(50) NOT NULL,
    ASSET_PATH VARCHAR(150) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100) NOT NULL,
    CONSTRAINT ASSET_TYPE_ID_FKEY FOREIGN KEY (ASSET_TYPE_ID) REFERENCES resourcehub.REF_TERM(ID)
);

